# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-14 20:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_conversation_thread_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='data',
            new_name='content',
        ),
    ]
